server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: ${APP_NAME:unnamed}
  datasource:
    url: jdbc:hsqldb:file:testdb
    username: sa
    password:
    dirver-class-name: org.hsqldb.jdbc.JDBCDriver
    # HikariCP配置:
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1
  ## 禁用自动配置
  datasource-master:
    url: jdbc:hsqldb:file:testdb
    username: sa
    password:
    dirver-class-name: org.hsqldb.jdbc.JDBCDriver
  datasource-slave:
    url: jdbc:hsqldb:file:testdb
    username: sa
    password:
    dirver-class-name: org.hsqldb.jdbc.JDBCDriver
pebble:
  suffix:
  cache: false

################################################################# 测试Conditional
#storage:
#  type: ${STORAGE_TYPE:local}
#  local:
#    root: ${STORAGE_LOCAL_ROOT:/var/storage}
#  aws:
#    buket: ${STORAGE_AWS_BUCKET:}
#    access-key: ${STORAGE_AWS_ACCESS_KEY:}
#    access-secret: ${STORAGE_AWS_ACCESS_SECRET:}
#  aliyun:
#    buket: ${STORAGE_ALIYUN_BUCKET:}
#    access-key: ${STORAGE_ALIYUN_ACCESS_KEY:}
#    access-secret: ${STORAGE_ALIYUN_ACCESS_SECRET:}

################################################################# 测试加载配置文件
storage:
  local:
    # 文件存储根目录:
    root-dir: ${STORAGE_LOCAL_ROOT:/var/storage}
    # 最大文件大小，默认100K:
    max-size: ${STORAGE_LOCAL_MAX_SIZE:102400}
    # 是否允许空文件:
    allow-empty: false
    # 允许的文件类型:
    allow-types: jpg, png, gif


---

spring:
  profiles: test

server:
  port: 8000

---

spring:
  profiles: production

server:
  port: 80

pebble:
  cache: true

